server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://hackerthon-db.cv2821t7oybx.ap-northeast-2.rds.amazonaws.com:3306/hackerthon?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: hackerthon-e
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    hibernate:
      naming:
        # Entity Table 대소문자 구분
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create # @Table 인 어노테이션 자동 생성
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # Initial Data config
    defer-datasource-initialization: true
  # 로그 레벨 설정
  logging:
    level:
      # hibernate 가 남기는 모든 로그가 debug모드로 설정
      # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
      org.hibernate.SQL: debug
      org.hibernate.type: trace # 실제 들
